"""Add column role_status to table roles

Revision ID: a69351b14f26
Revises: 71d4fd41f4c9
Create Date: 2025-06-17 16:46:54.829961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69351b14f26'
down_revision = '71d4fd41f4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'role_status')
    # ### end Alembic commands ###